server:
  port: 8083
spring:
  application:
    name: user-consumer
  cloud:
    loadbalancer:
      retry:
        enabled: true
eureka:
  client:
    service-url:
          defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    non-secure-port-enabled:10 #每10秒获取服务列表的服务
user-service:
  ribbon:
    ConnectTimeout: 250 # Ribbon的连接超时时间
    ReadTimeout: 1000 # Ribbon的数据读取超时时间
    OkToRetryOnAllOperations: true # 是否对所有操作都进行重试
    MaxAutoRetriesNextServer: 1 # 切换实例的重试次数
    MaxAutoRetries: 1 # 对当前实例的重试次数
logging:
  level:
    org.springframework: debug
    cn.ly: debug
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能
